  main = ".open-next/worker.js"
  name = "durio-tools"
  compatibility_date = "2025-07-22"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
  [observability.logs]
  enabled = true
  head_sampling_rate = 1